pipeline {
    agent {label 'aws-agent'}

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                echo 'Another command'
            }
        }
        stage('Test'){
            steps {
                echo 'Second stage'
            }
        }
    }
}