pipeline {
    agent {label 'aws-agent'}

    stages {
        stage('Installations') {
            steps {
                sudo yum install git
            }
        }
        stage('Clone'){
            steps {
                git clone 'https://github.com/dor-amar/jenkins.git'
            }
        }

    }
}