pipeline {


    agent {label 'aws-agent'}


    environment {
        DOCKERHUB_USERNAME = 'doramar97'
        DOCKERHUB_PASSWORD = credentials('my-docker-pass')
        DOCKERHUB_REPO = 'class-april'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'example', url: 'https://github.com/dor-amar/jenkins.git'
            }
        }


        stage('Build Docker Image') {
            steps {
                sh '''
                   cd ci-pipeline
                   sudo docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG .
                '''
            }
        }


        stage('Login to Docker Hub') {
            steps {
                sh '''
                   echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
                '''
            }
        }



        stage('Push Docker Image to Docker Hub') {
            steps {
                sh '''
                   docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG
                '''
            }
        }


        stage('Run Tests Before deployment') {
            steps {
                sh '''
                echo "Running some tests"
                '''

            }
        }

        stage('Deployment'){
           steps {
            sh'''
               docker run -d --rm -p 80:80 doramar97/class-april:${env.BUILD_NUMBER}
            '''
           }


        }








        // stage('Deploy Service with Ansible') {
        //     steps {
        //         sh '''
        //            ansible -i inventory/hosts -m shell -a "docker run -d --name app -p 80:80 $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG" all
        //         '''
        //     }
        // }
    }
}



