pipeline {
    agent any
    environment {
        DOCKERHUB_USERNAME = 'doramar97'
        DOCKERHUB_PASSWORD = credentials('dockerhub-password')
        DOCKERHUB_REPO = 'example-application'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/dor-amar/jenkins.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh '''
                   docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG .
                '''
            }
        }
        stage('Login to Docker Hub') {
            steps {
                sh '''
                   echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
                '''
            }
        }
        stage('Tag and Push Docker Image to Docker Hub') {
            steps {
                sh '''
                   docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG
                '''
            }
        }
    }
}
