pipeline {
    agent any

    stages {

        stage('Checkout code') {
            steps {
                git branch: 'main', url: 'https://github.com/dor-amar/jenkins'
            }
        }

        stage('Build Docker Image') {
            steps{
                sh'''
                ls
                cd august-pipeline
                docker build -t doramar97/myapp .
                docker images | grep doramar97
                '''
            }
        }
        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'DOCKERHUB_PASSWORD', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USERNAME')]) {
                    sh '''
                       echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
                    '''
                }
            }
        }
        stage('Push') {
            steps {
                    sh '''
                       docker push doramar97/myapp:latest
                    '''
          }
        }
        stage('Cleanup') {
            steps {
                sh '''
                docker rmi doramar97/myapp:latest
                '''
            }
        }
    }

}