---
- hosts: web
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull Flask app Docker image
      command: docker pull your_dockerhub_username/flask-app:latest

    - name: Run Flask app container
      docker_container:
        name: flask-app
        image: your_dockerhub_username/flask-app:latest
        state: started
        ports:
          - "5000:5000"
