# Use an official lightweight image as the base
FROM alpine:latest

# Set up a working directory
# WORKDIR /app

# # Create a script that outputs "Hello, World!"
# RUN echo 'echo "Hello, World!"' > hello.sh

# # Make the script executable
# RUN chmod +x hello.sh

# Define the command to run the script
CMD ["ls"]
