pipeline {
    agent { label 'aws-agent' }
    stages {
        stage('Run Build') {
            steps {
                sh 'cd run-on-agent-complex'
                sh './build.sh' 
            }
        }
    }
}