pipeline {
    agent { label 'aws-agent' }
    stages {
        stage('Run Build') {
            steps {
                sh 'sudo chmod +x run-on-agent-complex/build.sh'
                sh './run-on-agent-complex/build.sh' 
            }
        }
    }
}