pipeline {
    agent any
    environment {
        DOCKERHUB_USERNAME = 'doramar97'
        DOCKERHUB_REPO = 'example-application'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/dor-amar/jenkins.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh '''
                   docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG .
                '''
            }
        }
        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'DOCKERHUB_PASSWORD', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USERNAME')]) {
                    sh '''
                       echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
                    '''
                }
            }
        }
        stage('Tag and Push Docker Image to Docker Hub') {
            steps {
                sh '''
                   docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG
                '''
            }
        }
        stage('Deploy with Ansible') {
            steps {
                sh '''
                   ansible-playbook -i inventory/hosts deploy-playbook.yml --extra-vars "version=$IMAGE_TAG"
                '''
            }
        }
    }
}
